# Generated by Django 5.2.14 on 2026-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_configuracao_chave'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('rodando', 'Rodando'), ('ok', 'OK'), ('erro', 'Erro')], default='rodando', max_length=10)),
                ('iniciada_em', models.DateTimeField(db_index=True)),
                ('terminada_em', models.DateTimeField(blank=True, null=True)),
                ('duracao_ms', models.IntegerField(blank=True, null=True)),
                ('worker', models.CharField(blank=True, max_length=100)),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Execução de tarefa',
                'verbose_name_plural': 'Execuções de tarefas',
                'ordering': ['-iniciada_em'],
                'indexes': [models.Index(fields=['tarefa', '-iniciada_em'], name='core_execuc_tarefa_13c9cc_idx')],
            },
        ),
    ]
