# Generated by Django 5.2.14 on 2026-10-08 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_execucaotarefa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErroCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], max_length=10)),
                ('tela', models.CharField(blank=True, max_length=200)),
                ('mensagem', models.CharField(max_length=500)),
                ('stack', models.TextField(blank=True)),
                ('versao', models.CharField(blank=True, max_length=40)),
                ('dispositivo', models.CharField(blank=True, max_length=200)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Erro de cliente',
                'verbose_name_plural': 'Erros de cliente',
                'ordering': ['-criado_em'],
            },
        ),
    ]
