# Generated by Django 5.2.14 on 2026-10-07 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0014_pedido_codtra_pedido_transportadora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpressaoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('rede', 'Zebra de rede'), ('agente', 'Agente USB'), ('navegador', 'Navegador')], max_length=20)),
                ('status', models.CharField(choices=[('ok', 'Impressa'), ('erro', 'Erro')], max_length=10)),
                ('qtd_etiquetas', models.IntegerField(default=0)),
                ('automatica', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('impressora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressoes_etiqueta', to='pedidos.impressora')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressoes_etiqueta', to='pedidos.pedido')),
                ('print_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.printjob')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressoes_etiqueta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impressão de etiqueta',
                'verbose_name_plural': 'Impressões de etiqueta',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['pedido', 'status'], name='impressao_i_pedido__ca991d_idx')],
            },
        ),
    ]
