# Generated by Django 5.2.13 on 2026-04-28 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo_conexao', models.CharField(choices=[('rede', 'Rede (TCP/IP)'), ('usb', 'USB (via agent)')], max_length=10)),
                ('formato_preferido', models.CharField(choices=[('zpl', 'ZPL'), ('pdf', 'PDF')], default='zpl', max_length=5)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('porta', models.IntegerField(default=9100)),
                ('agent_id', models.CharField(blank=True, max_length=100)),
                ('dpi', models.IntegerField(default=203)),
                ('largura_mm', models.IntegerField(default=100)),
                ('altura_mm', models.IntegerField(default=150)),
                ('mesa', models.CharField(blank=True, max_length=50)),
                ('ativa', models.BooleanField(default=True)),
                ('ultimo_heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('mesa', models.CharField(blank=True, max_length=50)),
                ('qtd_pedidos', models.IntegerField(default=0)),
                ('etiquetador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to=settings.AUTH_USER_MODEL)),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.impressora')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_externo', models.CharField(max_length=100, unique=True)),
                ('cliente', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('separada', 'Separada'), ('faturado', 'Faturado'), ('aguardando_etiquetar', 'Aguardando etiquetar'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=30)),
                ('criado_em', models.DateTimeField()),
                ('separado_em', models.DateTimeField(blank=True, null=True)),
                ('faturado_em', models.DateTimeField(blank=True, null=True)),
                ('endereco_fisico', models.CharField(blank=True, max_length=20)),
                ('ordem_pilha', models.IntegerField(blank=True, null=True)),
                ('embalagem_enviada_em', models.DateTimeField(blank=True, null=True)),
                ('embalagem_tentativas', models.IntegerField(default=0)),
                ('embalagem_ultimo_erro', models.TextField(blank=True)),
                ('etiqueta_vtex_recebida_em', models.DateTimeField(blank=True, null=True)),
                ('etiqueta_vtex_tentativas', models.IntegerField(default=0)),
                ('etiqueta_vtex_ultimo_erro', models.TextField(blank=True)),
                ('etiqueta_impressa_em', models.DateTimeField(blank=True, null=True)),
                ('etiquetador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_etiquetados', to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.marketplace')),
                ('separador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_separados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EtiquetaVtex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(max_length=10)),
                ('conteudo', models.BinaryField()),
                ('recebida_em', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(max_length=64)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etiqueta_vtex', to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
                ('ean', models.CharField(blank=True, max_length=20)),
                ('qtd_pedida', models.IntegerField()),
                ('qtd_separada', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('cancelado', 'Cancelado'), ('falta', 'Em falta')], default='ok', max_length=20)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LotePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.lote')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('lote', 'pedido')},
            },
        ),
    ]
