# Generated by Django 5.2.13 on 2026-04-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotepedido',
            name='confirmado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
