# Generated by Django 5.2.13 on 2026-04-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_lotepedido_confirmado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('separando', 'Separando'), ('faturado', 'Faturado'), ('aguardando_etiquetar', 'Aguardando etiquetar'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=30),
        ),
    ]
