# Generated by Django 5.2.14 on 2026-08-27 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_rename_conferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='separador_nao_identificado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Separador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('apelido', models.CharField(blank=True, max_length=100)),
                ('documento', models.CharField(blank=True, max_length=30)),
                ('tipo', models.CharField(choices=[('extra', 'Extra'), ('funcionario', 'Funcionário')], default='extra', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separador_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Separador',
                'verbose_name_plural': 'Separadores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='separado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_separados', to='pedidos.separador'),
        ),
        migrations.CreateModel(
            name='SeparadorLiberacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('liberado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liberacoes_concedidas', to=settings.AUTH_USER_MODEL)),
                ('separador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liberacoes', to='pedidos.separador')),
            ],
            options={
                'verbose_name': 'Liberação diária',
                'verbose_name_plural': 'Liberações diárias',
                'ordering': ['-data'],
                'constraints': [models.UniqueConstraint(fields=('separador', 'data'), name='liberacao_unica_por_dia')],
            },
        ),
    ]
