# Generated by Django 5.2.14 on 2026-08-27 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedido_separador_nao_identificado_separador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='aberta', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequencias_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sequência',
                'verbose_name_plural': 'Sequências',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='sequencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos.sequencia'),
        ),
    ]
