# Generated by Django 5.2.14 on 2026-08-27 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_sequencia_pedido_sequencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('selecionado', 'Selecionado'), ('atribuido', 'Atribuído'), ('conferindo', 'Em conferência'), ('aguardando_fechamento', 'Aguardando fechamento'), ('conferido', 'Conferido'), ('nao_conforme', 'Não conforme'), ('cancelado', 'Cancelado'), ('faturado', 'Faturado'), ('aguardando_etiquetar', 'Aguardando etiquetar'), ('concluido', 'Concluído')], default='pendente', max_length=30),
        ),
        migrations.CreateModel(
            name='DivergenciaBarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_bipado', models.CharField(max_length=100)),
                ('qtd', models.IntegerField()),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divergencias', to='pedidos.pedidoitem')),
                ('vinculado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divergencias_liberadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Divergência de barra',
                'verbose_name_plural': 'Divergências de barra',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ErroSeparacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('a_mais', 'Sobra (a mais)'), ('a_menos', 'Falta (a menos)')], max_length=10)),
                ('qtd', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erros_separacao', to='pedidos.pedido')),
                ('pedido_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erros_separacao', to='pedidos.pedidoitem')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erros_registrados', to=settings.AUTH_USER_MODEL)),
                ('separador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erros_separacao', to='pedidos.separador')),
            ],
            options={
                'verbose_name': 'Erro de separação',
                'verbose_name_plural': 'Erros de separação',
                'ordering': ['-criado_em'],
            },
        ),
    ]
