# Generated by Django 5.2.14 on 2026-09-09 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_pedido_status_divergenciabarra_erroseparacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codfil',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codsnf',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='frete',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('pedido', 'Pedido'), ('nota_fiscal', 'Nota fiscal')], default='pedido', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_externo',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('tipo', 'codfil', 'codsnf', 'numero_externo'), name='pedido_identidade_senior'),
        ),
    ]
