# Generated by Django 5.2.14 on 2026-09-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pedido_codfil_pedido_codsnf_pedido_frete_pedido_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='frete',
            field=models.CharField(blank=True, choices=[('C', 'Entrega'), ('F', 'Retira'), ('X', 'Sem frete')], max_length=1),
        ),
    ]
