# Generated by Django 5.2.14 on 2026-09-30 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_pedido_frete_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cancelado_origem',
            field=models.CharField(blank=True, choices=[('senior', 'Cancelado no Senior'), ('supervisor', 'Cancelado pelo supervisor')], max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_anterior',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transferido_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferido_de_set', to='pedidos.pedido'),
        ),
    ]
